import { Section } from '../types';

export const etpSections: Section[] = [
  { id: 'etp-1-introducao', title: '1. Introdução', placeholder: 'Apresentação do objeto da contratação, forma de contratação, justificativa para o parcelamento ou não, e o posicionamento conclusivo sobre a adequação da contratação...', hasGen: true, hasRiskAnalysis: true, tooltip: "Descreva o problema a ser resolvido e a sua melhor solução, permitindo a avaliação da viabilidade técnica e econômica da contratação." },
  { id: 'etp-2-necessidade', title: '2. Descrição da Necessidade da Contratação', placeholder: 'Detalhe a necessidade da contratação, o problema a ser resolvido sob a perspectiva do interesse público...', hasGen: true, hasRiskAnalysis: true, tooltip: "Evidencie o problema identificado e a real necessidade que ele gera, bem como o que se almeja alcançar com a contratação." },
  { id: 'etp-3-requisitos', title: '3. Descrição dos Requisitos da Contratação', placeholder: 'Liste os requisitos da contratação necessários e suficientes à escolha da solução, como requisitos de negócio, legais e gerais da solução...', hasGen: true, hasRiskAnalysis: true, tooltip: "Defina os requisitos indispensáveis para que a solução atenda à necessidade, incluindo aspectos de negócio, legais e técnicos." },
  { id: 'etp-4-levantamento', title: '4. Levantamento de Mercado', placeholder: 'Análise das alternativas possíveis e justificativa técnica e econômica da escolha do tipo de solução a contratar...', hasGen: true, hasRiskAnalysis: true, tooltip: "Prospecção e análise das alternativas de soluções disponíveis no mercado que possam atender à necessidade." },
  { id: 'etp-5-solucao', title: '5. Descrição da Solução como um Todo', placeholder: 'Descrição da solução como um todo, inclusive das exigências relacionadas à manutenção e à assistência técnica, se for o caso...', hasGen: true, hasRiskAnalysis: true, tooltip: "Detalhe a solução escolhida, suas características, e como ela se alinha com os requisitos definidos." },
  { id: 'etp-6-estimativa-quantidades', title: '6. Estimativas das Quantidades a serem Contratadas', placeholder: 'Apresente as estimativas de quantidades, acompanhadas das memórias de cálculo e documentos de suporte...', hasGen: true, hasRiskAnalysis: true, tooltip: "Defina as quantidades a serem contratadas, com base em memórias de cálculo e justificativas que considerem a demanda e a economia de escala." },
  { id: 'etp-7-estimativa-valor', title: '7. Estimativa do Valor da Contratação', placeholder: 'Apresente a estimativa de valor da contratação, com preços unitários referenciais, memórias de cálculo e documentos de suporte...', hasGen: true, hasRiskAnalysis: true, tooltip: "Calcule o valor estimado da contratação, com base em ampla pesquisa de mercado (Painel de Preços, contratações similares, etc.)." },
  { id: 'etp-8-justificativa-parcelamento', title: '8. Justificativa para o Parcelamento ou não da Solução', placeholder: 'Justifique a decisão de parcelar ou não o objeto da contratação, considerando a viabilidade técnica e econômica...', hasGen: true, hasRiskAnalysis: true, tooltip: "Fundamente a decisão de agrupar ou dividir o objeto em lotes, visando a ampliação da competição e a obtenção de propostas mais vantajosas." },
  { id: 'etp-9-contratacoes-correlatas', title: '9. Contratações Correlatas e/ou Interdependentes', placeholder: 'Liste as contratações que guardam relação/afinidade com o objeto desta contratação, sejam elas já realizadas ou futuras...', hasGen: true, hasRiskAnalysis: true, tooltip: "Identifique outras contratações que possam impactar ou ser impactadas por esta, para garantir a compatibilidade e o planejamento integrado." },
  { id: 'etp-10-resultados-pretendidos', title: '10. Demonstrativo dos Resultados Pretendidos', placeholder: 'Descreva os resultados pretendidos em termos de economicidade e de melhor aproveitamento dos recursos...', hasGen: true, hasRiskAnalysis: true, tooltip: "Demonstre os ganhos que a Administração almeja com a contratação (ex: eficiência, economia, melhoria da qualidade do serviço)." },
  { id: 'etp-11-providencias', title: '11. Providências a serem Adotadas', placeholder: 'Liste as providências a serem adotadas pela administração previamente à celebração do contrato (capacitação de servidores, adequação do ambiente, etc.)...', hasGen: true, hasRiskAnalysis: true, tooltip: "Descreva as ações preparatórias necessárias para o sucesso da contratação e da futura gestão contratual." },
  { id: 'etp-12-impactos-ambientais', title: '12. Impactos Ambientais e Sustentabilidade', placeholder: 'Descrição de possíveis impactos ambientais e respectivas medidas mitigadoras, incluindo requisitos de sustentabilidade...', hasGen: true, hasRiskAnalysis: true, tooltip: "Analise os impactos ambientais da contratação e defina os critérios de sustentabilidade que deverão ser observados." },
  { id: 'etp-13-viabilidade', title: '13. Declaração de Viabilidade da Contratação', placeholder: 'Posicionamento conclusivo sobre a adequação e viabilidade da contratação para o atendimento da necessidade a que se destina...', hasGen: true, hasRiskAnalysis: true, tooltip: "Declare, com base em todo o estudo, a viabilidade ou inviabilidade da contratação." }
];

export const trSections: Section[] = [
    { id: 'tr-1-objeto', title: '1. Objeto', placeholder: 'Incluir a descrição resumida dos serviços, incluindo o(a) instalação e/ou montagem, implementação, treinamento, etc. se necessários...', hasGen: true, hasRiskAnalysis: true, tooltip: "Definição do objeto, quantitativos, prazo do contrato e, se for o caso, a possibilidade de sua prorrogação." },
    { id: 'tr-2-justificativa', title: '2. Justificativa da Contratação', placeholder: 'A contratação dos serviços se justifica pela necessidade de..., para o quantitativo de demanda previsto pela Unidade Requisitante...', hasGen: true, hasRiskAnalysis: true, tooltip: "Fundamentação da contratação, que consiste na referência aos estudos técnicos preliminares correspondentes." },
    { id: 'tr-3-natureza-objeto', title: '3. Natureza do Objeto', placeholder: 'Os serviços contemplados possuem padrões de desempenho e qualidade que podem ser objetivamente definidos por meio de especificações usuais no mercado...', hasGen: true, hasRiskAnalysis: true, tooltip: "Classificação do objeto como bem ou serviço comum ou especial." },
    { id: 'tr-4-execucao-requisitos', title: '4. Modelo de Execução e Requisitos', placeholder: 'Detalhamento do objeto, forma de execução, rotinas, materiais, cronograma, local, treinamento e suporte...', hasGen: true, hasRiskAnalysis: true, tooltip: "Modelo de execução do objeto, que consiste na definição de como o contrato deverá produzir os resultados pretendidos." },
    { id: 'tr-5-prazo-execucao', title: '5. Prazo de Execução dos Serviços', placeholder: 'O prazo de execução dos serviços será de X dias/meses, a contar da data indicada no Termo de Autorização de Início dos Serviços...', hasGen: true, hasRiskAnalysis: false, tooltip: "Prazo para a conclusão do objeto do contrato." },
    { id: 'tr-6-prazo-vigencia', title: '6. Prazo de Vigência do Contrato', placeholder: 'O prazo de vigência da contratação será de X meses, contados da data de início dos serviços...', hasGen: true, hasRiskAnalysis: false, tooltip: "Período de validade do contrato administrativo, admitidas prorrogações se previsto em lei e no edital." },
    { id: 'tr-7-garantia', title: '7. Garantia Contratual', placeholder: 'O contratado prestará garantia de execução do contrato, nos moldes do art. 96 da Lei Federal nº 14.133/21, no valor de X% do contrato...', hasGen: true, hasRiskAnalysis: true, tooltip: "Exigência de garantia para assegurar a plena execução do contrato, se aplicável." },
    { id: 'tr-8-obrigacoes', title: '8. Obrigações das Partes', placeholder: 'Descrever as obrigações da Contratada e do Contratante (TCE-RJ)...', hasGen: true, hasRiskAnalysis: true, tooltip: "Definição dos direitos e das responsabilidades das partes." },
    { id: 'tr-9-selecao-fornecedor', title: '9. Forma e Critérios de Seleção do Fornecedor', placeholder: 'O fornecedor será selecionado por meio de Licitação, na modalidade Pregão, forma Eletrônica, com critério de julgamento pelo Menor Preço...', hasGen: true, hasRiskAnalysis: false, tooltip: "Forma de seleção do fornecedor e critérios de julgamento da proposta." },
    { id: 'tr-10-consorcio-cooperativas', title: '10. Participação de Consórcio e Cooperativas', placeholder: 'Será admitida/vedada a participação de empresas em regime de consórcio ou cooperativas, conforme justificativa...', hasGen: true, hasRiskAnalysis: false, tooltip: "Regras para participação de consórcios ou cooperativas, se aplicável." },
    { id: 'tr-11-qualificacao-tecnica', title: '11. Qualificação Técnica Exigida', placeholder: 'Comprovação de capacidade técnica por meio de atestados, registro em entidade profissional competente, etc...', hasGen: true, hasRiskAnalysis: true, tooltip: "Requisitos de qualificação técnica para comprovação da aptidão do licitante." },
    { id: 'tr-12-vistoria-tecnica', title: '12. Vistoria Técnica', placeholder: 'Será facultada/exigida a realização de vistoria técnica, a ser agendada previamente...', hasGen: true, hasRiskAnalysis: false, tooltip: "Condições para a realização de vistoria, se necessária." },
    { id: 'tr-13-qualificacao-financeira', title: '13. Qualificação Econômico-Financeira', placeholder: 'Comprovação de boa situação financeira por meio de balanços, índices contábeis, patrimônio líquido mínimo, etc...', hasGen: true, hasRiskAnalysis: true, tooltip: "Requisitos de qualificação econômico-financeira para demonstrar a capacidade do licitante de cumprir as obrigações." },
    { id: 'tr-14-subcontratacao', title: '14. Da Subcontratação', placeholder: 'Será permitida/vedada a subcontratação parcial do objeto, até o limite de X% do valor do contrato...', hasGen: true, hasRiskAnalysis: true, tooltip: "Regras e limites para a subcontratação de parte do objeto, se admitida." },
    { id: 'tr-15-gestao-contrato', title: '15. Modelo de Gestão do Contrato', placeholder: 'O gerenciamento e a fiscalização do contrato caberão a servidores designados, que determinarão o necessário para a regularização de faltas ou defeitos...', hasGen: true, hasRiskAnalysis: true, tooltip: "Descrição de como a execução do objeto será acompanhada e fiscalizada pelo órgão ou entidade." },
    { id: 'tr-16-medicao-recebimento', title: '16. Critérios de Medição e Recebimento do Objeto', placeholder: 'O recebimento do objeto será realizado de forma provisória e definitiva, conforme prazos e condições estabelecidas...', hasGen: true, hasRiskAnalysis: false, tooltip: "Critérios de medição e de pagamento." },
    { id: 'tr-17-forma-pagamento', title: '17. Forma de Pagamento', placeholder: 'O pagamento será efetuado em parcelas, mediante crédito em conta corrente da Contratada, até o 30º dia após a atestação da nota fiscal...', hasGen: true, hasRiskAnalysis: false, tooltip: "Condições e prazos para o pagamento." },
    { id: 'tr-18-sancoes', title: '18. Sanções Administrativas', placeholder: 'O descumprimento das cláusulas sujeitará a contratada às sanções de advertência, multa, impedimento de licitar e contratar...', hasGen: true, hasRiskAnalysis: true, tooltip: "Penalidades cabíveis em caso de inexecução contratual." },
    { id: 'tr-19-sustentabilidade', title: '19. Sustentabilidade', placeholder: 'O fornecedor deverá cumprir as orientações da Instrução Normativa nº 1, de 2010, do MPDG, referente aos critérios de Sustentabilidade Ambiental...', hasGen: true, hasRiskAnalysis: true, tooltip: "Critérios de sustentabilidade a serem observados na execução do contrato." },
    { id: 'tr-20-orcamento', title: '20. Adequação Orçamentária', placeholder: 'As despesas decorrentes da contratação correrão à conta de recursos específicos consignados no Orçamento...', hasGen: false, hasRiskAnalysis: false, tooltip: "Indicação do crédito orçamentário para a despesa." },
    { id: 'tr-21-consideracoes-finais', title: '21. Considerações Finais', placeholder: 'O presente termo de referência foi concebido com base nas normas legais aplicadas à matéria e nas premissas recomendadas pelo Tribunal...', hasGen: true, hasRiskAnalysis: false, tooltip: "Cláusulas de encerramento do documento." },
    { id: 'tr-22-anexos', title: '22. Anexos', placeholder: 'Liste aqui referências a documentos complementares ou adicione notas sobre os arquivos anexados...', hasGen: false, isAttachmentSection: true, tooltip: "Espaço para relacionar e descrever os documentos que acompanham o Termo de Referência." }
];
