import { Template } from '../types';

export const etpTemplates: Template[] = [
  {
    id: 'etp-dispensa-fornecimento-continuo',
    name: '(DISPENSA ELETRÔNICA) - Aquisição - Fornecimento Contínuo',
    description: 'Modelo para aquisição de bens de fornecimento contínuo por meio de dispensa eletrônica de licitação.',
    type: 'etp',
    sections: {
      'etp-1-introducao': 'Este Estudo Técnico Preliminar (ETP) tem como objetivo planejar e fundamentar a contratação, por dispensa de licitação em razão do valor (Art. 75, II, da Lei nº 14.133/21), para aquisição de [descrever o bem, ex: material de escritório, café e açúcar] em regime de fornecimento contínuo, para suprir as necessidades de [órgão/setor].',
      'etp-2-necessidade': 'A necessidade da contratação decorre da demanda constante e essencial de [descrever o bem] para a manutenção das atividades administrativas/finalísticas de [órgão/setor], sendo um item de consumo/uso regular e indispensável para o funcionamento da repartição.',
      'etp-3-requisitos': '1. Requisitos de Negócio: Fornecimento contínuo e ininterrupto do bem, com entregas programadas ou sob demanda. 2. Requisitos Legais: Atendimento às normas sanitárias/técnicas aplicáveis (se houver). 3. Requisitos da Solução: O bem deve possuir as especificações técnicas, de qualidade e de embalagem mínimas descritas no Termo de Referência.',
      'etp-4-levantamento': 'Foi realizado levantamento de mercado que identificou diversas marcas e fornecedores para o bem desejado. A solução de aquisição por meio de fornecedores múltiplos se mostra viável. A escolha pela contratação via dispensa eletrônica se justifica pela celeridade e economicidade para aquisições de baixo valor.',
      'etp-5-solucao': 'A solução consiste na aquisição de [descrever o bem] por meio de contrato de fornecimento contínuo, com entregas parceladas mediante requisição (ordem de fornecimento), garantindo o suprimento conforme a demanda e evitando a necessidade de grandes estoques. O certame será realizado por dispensa com disputa eletrônica.',
      'etp-6-estimativa-quantidades': 'A estimativa de consumo anual é de [quantidade] unidades de [bem]. A memória de cálculo baseia-se no consumo médio dos últimos 12 meses, conforme registros de [sistema/documento], ajustado por [fator de ajuste, se houver].',
      'etp-7-estimativa-valor': 'A estimativa de valor da contratação é de R$ [valor], com base em pesquisa de preços realizada junto a [número] fornecedores e consulta a [Painel de Preços, Atas de SRP, etc.], conforme planilha anexa. O valor está abaixo do limite para dispensa de licitação.',
      'etp-8-justificativa-parcelamento': 'O objeto será licitado em item único (ou em lotes, se for o caso), pois [justificar, ex: a aquisição de forma conjunta garante maior economia de escala e simplifica a gestão contratual].',
      'etp-9-contratacoes-correlatas': 'Não foram identificadas contratações correlatas ou interdependentes que impactem ou sejam impactadas por esta aquisição.',
      'etp-10-resultados-pretendidos': 'Espera-se garantir o suprimento contínuo de [bem], evitando interrupções nas atividades, com economia de recursos por meio de uma contratação de baixo valor e processo simplificado e competitivo.',
      'etp-11-providencias': 'A Administração deverá designar um gestor e um fiscal para o contrato, responsáveis pelo recebimento dos bens e ateste das notas fiscais.',
      'etp-12-impactos-ambientais': 'O objeto da contratação possui baixo impacto ambiental. Serão observados critérios de sustentabilidade na escolha do produto, como [ex: embalagens recicláveis, certificações ambientais], sempre que possível e sem prejuízo à competitividade.',
      'etp-13-viabilidade': 'Com base nos elementos apresentados neste estudo, declara-se a viabilidade da contratação para o atendimento da necessidade exposta, por se tratar de solução comum de mercado e de baixo risco.'
    },
  },
  {
    id: 'etp-licitacao-fornecimento-continuo',
    name: '(LICITAÇÃO - inclusive SRP) - Aquisição - Fornecimento Contínuo',
    description: 'Modelo para aquisição de bens de fornecimento contínuo por meio de licitação, incluindo a modalidade de Sistema de Registro de Preços (SRP).',
    type: 'etp',
    sections: {
      'etp-1-introducao': 'Este Estudo Técnico Preliminar (ETP) visa planejar e fundamentar a contratação, por meio de licitação (Pregão Eletrônico, com possibilidade de Sistema de Registro de Preços - SRP), para aquisição de [descrever o bem] em regime de fornecimento contínuo.',
      'etp-2-necessidade': 'A necessidade desta contratação decorre da demanda recorrente e previsível de [descrever o bem] para a manutenção das atividades em diversas unidades deste órgão. A contratação visa garantir o suprimento regular e evitar aquisições emergenciais.',
      'etp-3-requisitos': 'A contratação deve assegurar o fornecimento de produtos que atendam aos padrões de qualidade e segurança definidos em normas técnicas. O fornecedor deve garantir a entrega nos locais e prazos definidos. O objeto deve possuir garantia mínima de [prazo].',
      'etp-4-levantamento': 'O levantamento de mercado indicou uma ampla variedade de fornecedores e marcas, caracterizando o objeto como comum e padronizável. A utilização do SRP é vantajosa, pois permite adesões e aquisições sob demanda, otimizando o planejamento e reduzindo custos de estocagem.',
      'etp-5-solucao': 'A solução proposta é a realização de Pregão Eletrônico para Registro de Preços, visando a assinatura de Ata de Registro de Preços com validade de 12 meses. As aquisições serão realizadas mediante emissão de Ordens de Fornecimento.',
      'etp-6-estimativa-quantidades': 'A estimativa de quantitativos para a contratação foi baseada no histórico de consumo das unidades participantes, projetado para o período de 12 meses. Memória de cálculo detalhada em anexo.',
      'etp-7-estimativa-valor': 'O valor estimado da contratação é de R$ [valor], obtido a partir de ampla pesquisa de mercado, incluindo cotações com fornecedores, consulta ao Painel de Preços do Governo Federal e a atas de registro de preços de outros órgãos.',
      'etp-8-justificativa-parcelamento': 'O objeto será dividido em lotes/itens para ampliar a competitividade e permitir a participação de empresas especializadas em diferentes linhas de produtos, conforme a natureza do objeto.',
      'etp-9-contratacoes-correlatas': 'Esta contratação está alinhada com [outras contratações, se houver, ex: contratação de serviços de manutenção que utilizam os bens a serem adquiridos].',
      'etp-10-resultados-pretendidos': 'Pretende-se obter economia de escala, agilidade nas aquisições, padronização dos bens e garantia de suprimento contínuo, alinhado ao planejamento estratégico do órgão.',
      'etp-11-providencias': 'Cabe à Administração promover o certame licitatório, gerenciar a Ata de Registro de Preços e designar fiscais para os contratos que vierem a ser celebrados.',
      'etp-12-impactos-ambientais': 'Serão incluídos no Termo de Referência requisitos de sustentabilidade, como a exigência de produtos com menor impacto ambiental, certificações e logística reversa, sempre que aplicável.',
      'etp-13-viabilidade': 'Diante do exposto, a contratação é considerada viável, pois atende a uma necessidade permanente da Administração, a solução é comum de mercado e o procedimento proposto é o mais adequado.'
    },
  },
  {
    id: 'etp-licitacao-engenharia',
    name: '(LICITAÇÃO) - Serviços de Engenharia',
    description: 'Modelo para o planejamento da contratação de serviços de engenharia (comuns ou especiais) por meio de licitação.',
    type: 'etp',
    sections: {
      'etp-1-introducao': 'O presente ETP tem como objeto o planejamento da contratação de serviços de engenharia para [descrever o serviço, ex: elaboração de projeto executivo de edificação, reforma de instalação elétrica, fiscalização de obra de infraestrutura], essencial para [descrever a finalidade].',
      'etp-2-necessidade': 'A necessidade da contratação advém da [descrever o problema, ex: degradação da infraestrutura atual, necessidade de adequação às normas técnicas, ausência de capacidade técnica interna para fiscalização], o que gera riscos à segurança e à eficiência operacional.',
      'etp-3-requisitos': 'A contratação exige que a empresa possua registro no CREA/CAU, comprove capacidade técnica por meio de atestados para serviços de natureza e complexidade compatíveis, e aloque profissionais qualificados com a devida Anotação de Responsabilidade Técnica (ART) ou Registro de Responsabilidade Técnica (RRT).',
      'etp-4-levantamento': 'O mercado para serviços de engenharia desta natureza é competitivo. Foram consultadas soluções como [ex: contratação de empresa especializada, contratação de profissional autônomo]. A contratação de pessoa jurídica se mostra mais adequada devido à complexidade e à necessidade de garantia.',
      'etp-5-solucao': 'A solução definida é a contratação de empresa de engenharia, por meio de licitação na modalidade [Concorrência/Pregão para serviços comuns de engenharia], para a execução completa dos serviços descritos no Projeto Básico/Termo de Referência.',
      'etp-6-estimativa-quantidades': 'Os quantitativos dos serviços estão detalhados na planilha orçamentária anexa, com as respectivas unidades de medida e memórias de cálculo, baseados no levantamento de campo e no escopo do projeto.',
      'etp-7-estimativa-valor': 'O valor estimado da contratação é de R$ [valor], calculado com base no Sistema Nacional de Pesquisa de Custos e Índices da Construção Civil (SINAPI) e/ou no Sistema de Custos Referenciais de Obras (SICRO), conforme planilha orçamentária detalhada.',
      'etp-8-justificativa-parcelamento': 'O objeto não será parcelado, pois trata-se de um serviço tecnicamente indivisível, cuja execução por diferentes empresas poderia comprometer a coesão e a segurança do resultado final.',
      'etp-9-contratacoes-correlatas': 'Esta contratação está vinculada à [ex: obra de construção do edifício X, aquisição dos equipamentos que serão instalados], sendo uma etapa precedente/subsequente necessária.',
      'etp-10-resultados-pretendidos': 'Com a contratação, almeja-se obter [ex: um projeto de alta qualidade, a garantia de segurança e funcionalidade da edificação, uma fiscalização eficaz que assegure o cumprimento do contrato da obra].',
      'etp-11-providencias': 'Providências necessárias: aprovação do Projeto Básico/Termo de Referência, reserva orçamentária e designação da comissão de licitação e da equipe de fiscalização.',
      'etp-12-impactos-ambientais': 'Os impactos ambientais da contratação são [descrever os impactos]. O projeto deverá prever medidas mitigadoras, como [ex: gestão de resíduos da construção, uso de materiais sustentáveis].',
      'etp-13-viabilidade': 'Conclui-se pela viabilidade técnica e econômica da contratação, indispensável para o alcance dos objetivos de interesse público aqui delineados.'
    },
  },
];

export const trTemplates: Template[] = [
  {
    id: 'tr-srp-mao-de-obra-dedicada',
    name: '(DI/LICITAÇÃO SRP) - Serviços com dedicação de mão de obra',
    description: 'Modelo de TR para contratação de serviços com mão de obra dedicada, via Dispensa, Inexigibilidade ou SRP.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Contratação de empresa especializada para prestação de serviços continuados de [natureza do serviço, ex: limpeza e conservação], com dedicação exclusiva de mão de obra, para atender às necessidades de [unidade/local], compreendendo o fornecimento de todos os materiais, equipamentos e mão de obra necessários, conforme condições e exigências estabelecidas neste Termo de Referência e seus anexos.',
      'tr-2-justificativa': 'A contratação justifica-se pela necessidade de manter a [finalidade, ex: operacionalidade, higiene, segurança] das instalações, sendo essencial para o bom desempenho das atividades institucionais, conforme ETP nº [número do ETP].',
      'tr-3-natureza-objeto': 'Os serviços são classificados como comuns, pois seus padrões de desempenho e qualidade podem ser objetivamente definidos por meio de especificações usuais de mercado.',
      'tr-4-execucao-requisitos': 'Os serviços deverão ser executados de forma contínua, de [dias da semana], no horário de [horário]. A contratada deverá alocar [quantidade] postos de trabalho, com a qualificação e atribuições descritas no Anexo I. Deverá fornecer todos os materiais de limpeza, uniformes e EPIs.',
      'tr-5-prazo-execucao': 'O prazo de execução dos serviços é contínuo e vigerá pelo mesmo prazo de vigência do contrato.',
      'tr-6-prazo-vigencia': 'O prazo de vigência da contratação será de 12 (doze) meses, contados da data de assinatura, podendo ser prorrogado por iguais e sucessivos períodos até o limite de 60 (sessenta) meses, nos termos do Art. 106 da Lei nº 14.133/21.',
      'tr-7-garantia': 'A contratada deverá prestar garantia de execução contratual no percentual de 5% (cinco por cento) sobre o valor total do contrato, nos moldes do art. 96 da Lei nº 14.133/21.',
      'tr-8-obrigacoes': 'Obrigações da Contratada: Alocar os profissionais conforme qualificação exigida; fornecer materiais e equipamentos; cumprir as obrigações trabalhistas e previdenciárias. Obrigações do Contratante: Efetuar os pagamentos em dia; fiscalizar a execução dos serviços; disponibilizar as áreas e condições necessárias.',
      'tr-9-selecao-fornecedor': 'A seleção do fornecedor será por meio de [Pregão Eletrônico para Registro de Preços / Contratação Direta por Dispensa/Inexigibilidade], com critério de julgamento pelo Menor Preço (ou Maior Desconto).',
      'tr-10-consorcio-cooperativas': 'Será [admitida/vedada] a participação de empresas em consórcio. Será [admitida/vedada] a participação de cooperativas.',
      'tr-11-qualificacao-tecnica': 'A licitante/contratada deverá comprovar aptidão para o desempenho de atividade pertinente e compatível em características, quantidades e prazos com o objeto da licitação, mediante a apresentação de atestados fornecidos por pessoas jurídicas de direito público ou privado.',
      'tr-12-vistoria-tecnica': 'Será [facultada/exigida] a realização de vistoria técnica nas instalações, a ser agendada previamente, para que as licitantes possam ter pleno conhecimento das condições e peculiaridades do local de prestação dos serviços.',
      'tr-13-qualificacao-financeira': 'A licitante/contratada deverá comprovar boa situação financeira através da apresentação de [Balanço Patrimonial, índices contábeis, etc.], conforme definido no edital/ato convocatório.',
      'tr-14-subcontratacao': 'É vedada a subcontratação do objeto deste contrato.',
      'tr-15-gestao-contrato': 'A gestão e fiscalização do contrato serão realizadas por servidores formalmente designados (gestor e fiscal), aos quais competirá acompanhar a execução, registrar ocorrências, atestar as medições e solicitar providências à contratada.',
      'tr-16-medicao-recebimento': 'O recebimento dos serviços será realizado mensalmente, após a medição e verificação da conformidade pela fiscalização. O recebimento definitivo se dará após o ateste do fiscal do contrato.',
      'tr-17-forma-pagamento': 'O pagamento será efetuado mensalmente, até o [dia] dia útil do mês subsequente ao da prestação dos serviços, após a apresentação da nota fiscal devidamente atestada pela fiscalização.',
      'tr-18-sancoes': 'O descumprimento das obrigações contratuais sujeitará a contratada às sanções de advertência, multa, impedimento de licitar e contratar e declaração de inidoneidade, nos termos dos artigos 155 e 156 da Lei nº 14.133/21 e das condições do edital.',
      'tr-19-sustentabilidade': 'A contratada deverá adotar práticas de sustentabilidade, como o uso de produtos biodegradáveis, a gestão de resíduos e o consumo consciente de água e energia.',
      'tr-20-orcamento': 'As despesas decorrentes desta contratação correrão à conta da dotação orçamentária: [informar a dotação].',
      'tr-21-consideracoes-finais': 'O presente Termo de Referência foi elaborado com base nas melhores práticas e em estrita observância à Lei nº 14.133/2021, buscando a contratação mais vantajosa para a Administração Pública.',
      'tr-22-anexos': 'Fazem parte deste Termo de Referência os seguintes anexos: Anexo I - Detalhamento dos Serviços e Qualificação da Mão de Obra; Anexo II - Planilha de Custos e Formação de Preços; Anexo III - Modelo de Proposta.'
    },
  },
  {
    id: 'tr-licitacao-servicos-mao-de-obra',
    name: '(LICITAÇÃO) - Serviços com dedicação de mão de obra',
    description: 'Modelo de TR para licitar serviços continuados com alocação de mão de obra residente.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Contratação de empresa especializada para a prestação de serviços continuados de [natureza do serviço, ex: portaria, recepção], com dedicação exclusiva de mão de obra, para atender às necessidades de [unidade/local], compreendendo o fornecimento de todos os materiais, equipamentos e mão de obra necessários.',
      'tr-2-justificativa': 'A contratação justifica-se pela necessidade de [finalidade, ex: controlar o acesso, organizar o fluxo de pessoas] nas instalações, sendo essencial para a segurança e organização do ambiente, conforme ETP nº [número do ETP].',
      'tr-3-natureza-objeto': 'Os serviços são classificados como comuns, pois seus padrões de desempenho e qualidade podem ser objetivamente definidos por meio de especificações usuais de mercado.',
      'tr-4-execucao-requisitos': 'Os serviços deverão ser executados de forma contínua, 24 horas por dia, 7 dias por semana, em regime de escala. A contratada deverá alocar [quantidade] postos de trabalho, com a qualificação e atribuições descritas no Anexo I. Deverá fornecer uniformes e equipamentos de comunicação.',
      'tr-5-prazo-execucao': 'O prazo de execução dos serviços é contínuo e vigerá pelo mesmo prazo de vigência do contrato.',
      'tr-6-prazo-vigencia': 'O prazo de vigência da contratação será de 12 (doze) meses, contados da data de assinatura, podendo ser prorrogado por iguais e sucessivos períodos até o limite legal.',
      'tr-7-garantia': 'A contratada deverá prestar garantia de execução contratual no percentual de 5% (cinco por cento) sobre o valor total do contrato, nos moldes do art. 96 da Lei nº 14.133/21.',
      'tr-8-obrigacoes': 'Obrigações da Contratada: Cumprir a escala de trabalho sem falhas; treinar os funcionários; cumprir as obrigações trabalhistas. Obrigações do Contratante: Pagar em dia; fiscalizar os postos; comunicar ocorrências.',
      'tr-9-selecao-fornecedor': 'A seleção do fornecedor será por meio de Licitação, na modalidade Pregão Eletrônico, com critério de julgamento pelo Menor Preço.',
      'tr-10-consorcio-cooperativas': 'Não será admitida a participação de empresas em consórcio ou de cooperativas, dada a natureza do serviço.',
      'tr-11-qualificacao-tecnica': 'A licitante deverá comprovar experiência na prestação de serviços com características semelhantes, mediante apresentação de atestados.',
      'tr-12-vistoria-tecnica': 'A realização de vistoria técnica é facultada às licitantes, mediante agendamento prévio.',
      'tr-13-qualificacao-financeira': 'Será exigida comprovação de qualificação econômico-financeira, incluindo Capital Social ou Patrimônio Líquido mínimo de 10% do valor do contrato.',
      'tr-14-subcontratacao': 'É vedada a subcontratação do objeto deste contrato.',
      'tr-15-gestao-contrato': 'A fiscalização será exercida por um ou mais servidores designados, que serão responsáveis pelo acompanhamento diário dos postos, controle de frequência, e ateste dos serviços para pagamento.',
      'tr-16-medicao-recebimento': 'A medição será mensal, com base na folha de ponto e no relatório de ocorrências, conferidos e atestados pela fiscalização.',
      'tr-17-forma-pagamento': 'O pagamento será realizado mensalmente, após o ateste da nota fiscal pela fiscalização, em conta corrente da contratada.',
      'tr-18-sancoes': 'A inexecução total ou parcial do contrato sujeitará a contratada a sanções, incluindo multas e impedimento de contratar com a Administração, garantido o contraditório e a ampla defesa.',
      'tr-19-sustentabilidade': 'Não se aplica diretamente, mas a contratada deve seguir as normas de segurança do trabalho e de descarte de resíduos.',
      'tr-20-orcamento': 'A despesa correrá por conta da dotação orçamentária: [informar a dotação].',
      'tr-21-consideracoes-finais': 'Este documento estabelece as condições para a contratação, buscando a máxima eficiência e economicidade para a Administração.',
      'tr-22-anexos': 'Anexo I - Detalhamento dos Postos de Serviço. Anexo II - Planilha de Custos e Formação de Preços.'
    },
  },
  {
    id: 'tr-dispensa-inex-servico-sem-mao-obra',
    name: '(DISPENSA E INEXIGIBILIDADE) - Serviço sem mão de obra dedicada',
    description: 'Modelo de TR para serviços pontuais ou continuados sem dedicação de mão de obra, por contratação direta.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Contratação de empresa para prestação de serviços técnicos de [natureza do serviço, ex: manutenção corretiva de elevadores, consultoria jurídica especializada, licenciamento de software], a serem executados sob demanda e sem regime de dedicação exclusiva de mão de obra.',
      'tr-2-justificativa': 'A contratação direta se justifica por [Inexigibilidade - Art. 74 / Dispensa - Art. 75], pois [detalhar o motivo, ex: trata-se de fornecedor exclusivo, serviço técnico de notória especialização, valor abaixo do limite para dispensa]. A contratação é necessária para [objetivo].',
      'tr-3-natureza-objeto': 'O serviço é classificado como [comum/especial/técnico especializado de natureza intelectual].',
      'tr-4-execucao-requisitos': 'A execução se dará mediante a emissão de Ordem de Serviço. A contratada deverá [descrever as principais obrigações e requisitos da execução]. O serviço deve ser concluído em até [prazo] dias após o chamado.',
      'tr-5-prazo-execucao': 'O prazo de execução de cada chamado será de [prazo], conforme Ordem de Serviço.',
      'tr-6-prazo-vigencia': 'O prazo de vigência do contrato será de [prazo, ex: 12 meses], permitindo a emissão de Ordens de Serviço durante este período.',
      'tr-7-garantia': 'A garantia dos serviços prestados será de, no mínimo, [prazo, ex: 90 dias] contra defeitos de execução.',
      'tr-8-obrigacoes': 'Obrigações da Contratada: Executar o serviço com a qualidade técnica exigida, cumprir os prazos. Obrigações do Contratante: Prestar as informações necessárias, realizar o pagamento após o ateste.',
      'tr-9-selecao-fornecedor': 'A escolha do fornecedor recaiu sobre a empresa [nome da empresa] pela razão de [justificativa detalhada da escolha, ex: ser a única representante da marca no país, possuir notória especialização comprovada por...].',
      'tr-10-consorcio-cooperativas': 'Não se aplica.',
      'tr-11-qualificacao-tecnica': 'A empresa comprova sua qualificação técnica por meio de [descrever os documentos: atestados, certidões, currículo dos profissionais].',
      'tr-12-vistoria-tecnica': 'Não se aplica.',
      'tr-13-qualificacao-financeira': 'A empresa demonstra sua saúde financeira por meio de [descrever documentos, se exigido]. Foi comprovada a regularidade fiscal e trabalhista.',
      'tr-14-subcontratacao': 'É vedada a subcontratação do objeto.',
      'tr-15-gestao-contrato': 'A gestão e fiscalização do contrato serão realizadas por servidor designado, que será responsável por emitir as Ordens de Serviço, acompanhar a execução e atestar a conclusão para fins de pagamento.',
      'tr-16-medicao-recebimento': 'O recebimento ocorrerá após a conclusão de cada Ordem de Serviço, mediante verificação da conformidade com o solicitado e emissão de Termo de Recebimento Definitivo.',
      'tr-17-forma-pagamento': 'O pagamento será realizado por Ordem de Serviço executada, após a apresentação da respectiva nota fiscal, devidamente atestada pelo fiscal do contrato.',
      'tr-18-sancoes': 'O descumprimento das obrigações sujeitará a contratada às sanções previstas na Lei nº 14.133/21.',
      'tr-19-sustentabilidade': 'A contratada deverá, na execução dos serviços, observar as normas ambientais aplicáveis, especialmente quanto ao descarte de materiais.',
      'tr-20-orcamento': 'A despesa está programada na dotação orçamentária [informar a dotação]. A justificativa de preço está anexa, comprovando a compatibilidade com os valores de mercado.',
      'tr-21-consideracoes-finais': 'Este documento detalha as condições necessárias para a contratação direta, em conformidade com a legislação.',
      'tr-22-anexos': 'Anexo I - Proposta da Contratada. Anexo II - Documentos de Habilitação. Anexo III - Justificativa de Preço.'
    },
  },
  {
    id: 'tr-licitacao-sem-mao-de-obra-residente',
    name: '(LICITAÇÃO) Serviços sem mão de obra residente',
    description: 'Modelo de TR para licitar serviços que não exigem a alocação permanente de funcionários nas dependências do contratante.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Contratação de empresa especializada para a prestação de serviços de [natureza do serviço, ex: manutenção de software, recarga de extintores, confecção de material gráfico], executados de forma não contínua e sem mão de obra residente, visando o atendimento de demandas específicas do órgão.',
      'tr-2-justificativa': 'A contratação se faz necessária para [objetivo, ex: garantir o funcionamento de sistemas críticos, cumprir normas de segurança, divulgar ações institucionais], atividades que demandam conhecimento técnico específico não disponível no quadro de pessoal do órgão. Conforme ETP nº [número].',
      'tr-3-natureza-objeto': 'Os serviços são classificados como comuns, passíveis de definição objetiva por meio de especificações de mercado.',
      'tr-4-execucao-requisitos': 'A prestação dos serviços ocorrerá sob demanda, mediante emissão de Ordem de Serviço (OS). A contratada deverá iniciar a execução em até [prazo] após o recebimento da OS e concluí-la no prazo estipulado. Os requisitos técnicos e de qualidade estão detalhados no Anexo I.',
      'tr-5-prazo-execucao': 'O prazo de execução de cada serviço será definido na respectiva Ordem de Serviço.',
      'tr-6-prazo-vigencia': 'O contrato terá vigência de 12 (doze) meses, podendo ser prorrogado, a critério da Administração.',
      'tr-7-garantia': 'Exige-se garantia de execução contratual no percentual de 5% do valor do contrato. Adicionalmente, cada serviço executado terá garantia mínima de [prazo].',
      'tr-8-obrigacoes': 'Obrigações da Contratada: Cumprir os prazos e os níveis de qualidade definidos; fornecer todo o ferramental e pessoal necessário. Obrigações do Contratante: Fornecer as informações para a execução; realizar os pagamentos pontualmente.',
      'tr-9-selecao-fornecedor': 'A seleção será por meio de Pregão Eletrônico, critério de julgamento de Menor Preço por item/lote.',
      'tr-10-consorcio-cooperativas': 'Não será permitida a participação de empresas em consórcio.',
      'tr-11-qualificacao-tecnica': 'Será exigida a apresentação de atestados de capacidade técnica que comprovem a execução anterior de serviços compatíveis em características com o objeto da licitação.',
      'tr-12-vistoria-tecnica': 'Não se aplica, pois a execução não depende das especificidades físicas das instalações do contratante.',
      'tr-13-qualificacao-financeira': 'A qualificação econômico-financeira será comprovada conforme exigências do edital, de acordo com a legislação vigente.',
      'tr-14-subcontratacao': 'Não será permitida a subcontratação do objeto principal do contrato.',
      'tr-15-gestao-contrato': 'A fiscalização será exercida por servidor designado, que será o ponto de contato para a emissão de Ordens de Serviço, acompanhamento, e ateste para pagamento.',
      'tr-16-medicao-recebimento': 'O recebimento de cada serviço será feito mediante termo de recebimento definitivo, assinado pelo fiscal, após a verificação de que o objeto foi executado conforme o solicitado.',
      'tr-17-forma-pagamento': 'O pagamento será realizado por serviço efetivamente executado e recebido, após a apresentação da nota fiscal correspondente.',
      'tr-18-sancoes': 'O atraso ou a execução em desconformidade com o especificado sujeitará a contratada às penalidades previstas na Lei 14.133/21 e no edital.',
      'tr-19-sustentabilidade': 'A contratada deverá priorizar, sempre que possível, o uso de materiais e técnicas de menor impacto ambiental.',
      'tr-20-orcamento': 'As despesas estimadas correrão à conta da dotação: [informar a dotação].',
      'tr-21-consideracoes-finais': 'As condições estabelecidas neste Termo de Referência visam assegurar uma contratação eficiente e vantajosa.',
      'tr-22-anexos': 'Anexo I - Especificações Técnicas dos Serviços. Anexo II - Modelo de Ordem de Serviço.'
    },
  },
  {
    id: 'tr-srp-sem-mao-de-obra-residente',
    name: '(LICITAÇÃO SRP) - Serviços sem mão de obra residente',
    description: 'Modelo de TR para licitar, via Sistema de Registro de Preços, serviços que não exigem alocação permanente de funcionários.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Registro de Preços para futura e eventual contratação de empresa especializada na prestação de serviços de [natureza do serviço, ex: chaveiro, desinsetização, locação de equipamentos para eventos], a serem executados sob demanda, sem alocação de mão de obra residente.',
      'tr-2-justificativa': 'A utilização do Sistema de Registro de Preços (SRP) é justificada pela necessidade frequente, porém não contínua, de tais serviços. O SRP confere agilidade e economicidade, permitindo a contratação somente quando houver demanda efetiva. (ETP nº [número]).',
      'tr-3-natureza-objeto': 'Trata-se de serviços comuns, cujas especificações podem ser objetivamente definidas no edital.',
      'tr-4-execucao-requisitos': 'A execução dos serviços ocorrerá mediante a emissão de Ordem de Serviço (OS), conforme a necessidade da Administração. A contratada deverá atender aos chamados nos prazos e condições de qualidade definidos no Anexo I - Especificações Técnicas.',
      'tr-5-prazo-execucao': 'O prazo de execução para cada tipo de serviço está definido no Anexo I, a contar do recebimento da Ordem de Serviço.',
      'tr-6-prazo-vigencia': 'A Ata de Registro de Preços terá vigência de 12 (doze) meses, não sendo prorrogada. Os contratos decorrentes da Ata terão a vigência necessária para a conclusão do serviço solicitado.',
      'tr-7-garantia': 'Poderá ser exigida garantia de execução para os contratos assinados a partir da Ata, conforme o vulto e a complexidade do serviço específico, a ser definido no edital.',
      'tr-8-obrigacoes': 'Obrigações do Detentor da Ata: Manter os preços e condições da proposta durante a vigência da Ata; atender às Ordens de Serviço emitidas. Obrigações do Contratante: Emitir a OS com clareza; realizar o pagamento após a devida execução.',
      'tr-9-selecao-fornecedor': 'A seleção será por Pregão Eletrônico para Registro de Preços, com critério de julgamento de Menor Preço por item.',
      'tr-10-consorcio-cooperativas': '[Definir se será permitida ou vedada a participação de consórcios e/ou cooperativas].',
      'tr-11-qualificacao-tecnica': 'Exigir-se-á a comprovação de aptidão técnica por meio de atestados para serviços de natureza similar ao objeto licitado.',
      'tr-12-vistoria-tecnica': 'Não será exigida vistoria técnica.',
      'tr-13-qualificacao-financeira': 'As licitantes deverão apresentar os documentos de qualificação econômico-financeira previstos no edital para demonstrar sua capacidade de cumprir as futuras obrigações.',
      'tr-14-subcontratacao': 'Será [permitida/vedada] a subcontratação, conforme condições a serem estabelecidas no edital.',
      'tr-15-gestao-contrato': 'A gestão da Ata será de responsabilidade do órgão gerenciador. A fiscalização de cada contrato decorrente da Ata caberá ao órgão solicitante, por meio de servidor designado.',
      'tr-16-medicao-recebimento': 'O recebimento de cada serviço será formalizado pelo fiscal do contrato, que atestará a execução conforme a Ordem de Serviço.',
      'tr-17-forma-pagamento': 'O pagamento será efetuado após a conclusão e recebimento de cada serviço, mediante apresentação de nota fiscal.',
      'tr-18-sancoes': 'O detentor da Ata que se recusar a assinar o contrato ou não cumprir uma Ordem de Serviço estará sujeito às sanções de cancelamento do registro e outras penalidades previstas em lei.',
      'tr-19-sustentabilidade': 'Sempre que possível, os serviços deverão ser executados com observância às normas de sustentabilidade ambiental.',
      'tr-20-orcamento': 'O orçamento estimado para os quantitativos máximos a serem registrados consta em anexo. As despesas correrão por conta das dotações orçamentárias dos órgãos participantes.',
      'tr-21-consideracoes-finais': 'Este TR visa a instruir o processo de Registro de Preços em conformidade com o Art. 82 e seguintes da Lei nº 14.133/21.',
      'tr-22-anexos': 'Anexo I - Especificações Técnicas dos Serviços e Prazos. Anexo II - Estimativa de Quantidades. Anexo III - Minuta da Ata de Registro de Preços.'
    },
  },
];
