import { Template } from '../types';

export const etpTemplates: Template[] = [
  {
    id: 'etp-ti-equipment',
    name: 'Aquisição de Equipamentos de TI',
    description: 'Template para compra de computadores, notebooks, servidores ou outros equipamentos de informática.',
    type: 'etp',
    sections: {
      'etp-1': 'Este Estudo Técnico Preliminar (ETP) visa a analisar a viabilidade e definir os requisitos para a contratação de uma solução de modernização do parque tecnológico da instituição, por meio da aquisição de notebooks. O objetivo é subsidiar a elaboração do Termo de Referência para a referida aquisição, sob a coordenação do Departamento de Tecnologia da Informação.',
      'etp-2': 'A necessidade da contratação decorre da obsolescência dos equipamentos de computação pessoal atualmente em uso na instituição, muitos dos quais com mais de 4 anos de utilização. Este cenário acarreta lentidão na execução de tarefas, incompatibilidade com softwares modernos, aumento dos custos de manutenção corretiva e vulnerabilidades de segurança. A não contratação implicaria em contínua perda de produtividade dos servidores, elevação dos riscos de incidentes de segurança da informação e prejuízo à imagem da instituição.',
      'etp-3': 'Departamento de Tecnologia da Informação (DTI) e Departamento de Administração (DA).',
      'etp-4': '**Requisitos de Negócio:**\n- Prover aos servidores equipamentos que suportem o regime de trabalho híbrido (presencial e remoto).\n- Garantir a execução de softwares de produtividade, videochamada e sistemas corporativos sem travamentos.\n\n**Requisitos Legais:**\n- Atendimento à Lei Geral de Proteção de Dados (LGPD) com recursos de segurança embarcados.\n- Garantia do produto em conformidade com o Código de Defesa do Consumidor.\n\n**Requisitos Gerais:**\n- Garantia técnica mínima de 36 meses, modalidade on-site.\n- Equipamentos devem ser novos e de primeiro uso.',
      'etp-5': 'Foram analisadas as seguintes soluções de mercado:\n1. **Aquisição de notebooks:** Compra definitiva dos equipamentos.\n2. **Locação de notebooks (HaaS - Hardware as a Service):** Contratação de serviço que inclui os equipamentos e manutenção.\n\n**Análise Comparativa:**\n- **Custo:** A aquisição (Solução 1) apresenta um custo total de propriedade (TCO) menor em um horizonte de 4 anos.\n- **Gestão:** A locação (Solução 2) simplifica a gestão de ativos e manutenção.\n\n**Justificativa da Escolha:** Opta-se pela **Solução 1 (Aquisição)**, pois o menor TCO representa maior economicidade para a Administração a longo prazo, e a estrutura de TI interna possui capacidade para gerenciar os ativos adquiridos.',
      'etp-6': 'A solução escolhida consiste na aquisição de notebooks corporativos com especificações técnicas que garantam performance e longevidade. Será exigido dos licitantes atestado de capacidade técnica para fornecimento de equipamentos de TI, a fim de assegurar que a empresa possui experiência prévia em contratações de porte similar, minimizando riscos de entrega e de qualidade.',
      'etp-7': 'A estimativa de 50 (cinquenta) unidades baseia-se no levantamento realizado pelo setor de patrimônio, que identificou 50 equipamentos com mais de 4 anos de uso e fora do período de garantia, os quais apresentam problemas recorrentes de performance e hardware. (Vide Memorando anexo).',
      'etp-8': 'A estimativa de valor foi realizada com base em ampla pesquisa de mercado, conforme detalhado:\n- **Painel de Preços do Governo Federal:** Mediana de preços para item similar: R$ 5.200,00.\n- **Contratações Similares (PNCP):** Valor médio em 3 contratos de outros órgãos: R$ 4.950,00.\n- **Pesquisa com Fornecedores:** Média de 3 cotações: R$ 5.100,00.\nAdotando-se a média ponderada, o valor de referência unitário é de R$ 5.000,00, totalizando um valor estimado de **R$ 250.000,00** para 50 unidades.',
      'etp-9': 'A contratação não será parcelada, sendo realizada em lote único. A justificativa para esta decisão reside na necessidade de padronização tecnológica dos equipamentos. A aquisição de um mesmo modelo de notebook para todos os usuários facilita a criação de imagens de sistema, a gestão de drivers, o suporte técnico e a manutenção, além de simplificar a gestão de garantias e gerar economia de escala na aquisição.',
      'etp-10': 'Esta contratação é interdependente da contratação de licenças de sistema operacional e de softwares de produtividade, cujos processos já estão em andamento. Não há outras contratações correlatas que impactem ou sejam impactadas diretamente por esta aquisição.',
      'etp-11': 'A presente contratação está alinhada ao Plano de Contratações Anual (PCA) 2024, item de necessidade nº 42, e ao Plano Diretor de Tecnologia da Informação (PDTI) 2024-2025, no que tange ao objetivo estratégico OE-03: "Modernizar a Infraestrutura de Tecnologia da Informação e Comunicação".',
      'etp-12': 'Os resultados pretendidos são:\n- **Economicidade:** Redução de 50% nos custos anuais com manutenção corretiva de computadores.\n- **Eficiência:** Aumento da produtividade dos servidores, com redução estimada de 15% no tempo gasto em tarefas que dependem de processamento computacional.\n- **Eficácia:** Melhoria do nível de segurança da informação da instituição, com a mitigação de vulnerabilidades presentes em equipamentos obsoletos.',
      'etp-13': 'Antes da celebração do contrato, o Departamento de Administração deverá realizar as seguintes providências:\n- Organizar o espaço físico no almoxarifado para o recebimento e armazenamento temporário dos equipamentos.\n- Elaborar, em conjunto com o setor de patrimônio, o plano de recolhimento dos equipamentos antigos a serem substituídos.\n- Designar formalmente o fiscal técnico e o fiscal administrativo do contrato.',
      'etp-14': 'Serão incluídos como requisitos de sustentabilidade:\n- Os equipamentos deverão possuir certificação de eficiência energética (ex: selo Procel ou Energy Star).\n- O fornecedor deverá apresentar um plano de logística reversa para as embalagens dos produtos, garantindo seu descarte ambientalmente adequado.',
      'etp-15': 'Diante do exposto, conclui-se pela **viabilidade** da contratação para aquisição de notebooks, por ser a solução que melhor atende à necessidade da Administração, alinhada ao seu planejamento, tecnicamente justificada e economicamente vantajosa.',
    },
  },
];

export const trTemplates: Template[] = [
  {
    id: 'tr-notebooks',
    name: 'Aquisição de Notebooks',
    description: 'Modelo detalhado para a compra de computadores portáteis para uso institucional.',
    type: 'tr',
    sections: {
      'tr-1': '**1.1 Objeto:** Aquisição de 50 (cinquenta) notebooks corporativos, novos e de primeiro uso, incluindo garantia técnica on-site de 36 meses, conforme especificações técnicas detalhadas no Anexo I deste Termo de Referência.\n**1.3 Regime de Execução:** Empreitada por preço unitário.',
      'tr-2': '**2.1 Justificativa:** A contratação é necessária para a modernização do parque tecnológico desta instituição, em conformidade com o Plano Diretor de TI, visando substituir equipamentos obsoletos que apresentam lentidão, falhas constantes e riscos de segurança. A fundamentação completa para a escolha desta solução encontra-se no Estudo Técnico Preliminar nº 123/2024.',
      'tr-3': '**3.1 Natureza do Objeto:** O objeto desta contratação é classificado como um bem comum, pois seus padrões de desempenho e qualidade podem ser objetivamente definidos por meio de especificações usuais de mercado, conforme detalhado no Anexo I.',
      'tr-4': '**4.1 Detalhamento do Objeto:** As especificações técnicas mínimas, de qualidade e de desempenho para os notebooks estão detalhadas no Anexo I.\n**4.2 Forma de Execução:** A entrega deverá ser única, no prazo estipulado, e os bens devem ser novos, sem uso, em embalagens originais e lacradas.\n**4.8 Garantia:** A garantia técnica mínima exigida é de 36 (trinta e seis) meses, modalidade "on-site", com atendimento em até 48 horas úteis.',
      'tr-5': '**5.1 Prazo de Execução:** O prazo para a entrega total dos 50 (cinquenta) notebooks será de até 30 (trinta) dias corridos, contados a partir da data de assinatura do contrato.',
      'tr-6': '**6.1 Prazo de Vigência:** O prazo de vigência do contrato será de 12 (doze) meses, contados da sua assinatura, não sendo prorrogável. Este prazo visa a garantir o acompanhamento da entrega e o início da garantia.',
      'tr-7': '**7.1 Garantia de Execução:** Será exigida da contratada a prestação de garantia de execução no valor correspondente a 5% (cinco por cento) do valor total do contrato, em uma das modalidades previstas no art. 96 da Lei nº 14.133/2021.',
      'tr-8': '**8.1 Obrigações da Contratada:** Entregar os bens em conformidade com as especificações; cumprir os prazos; prestar a garantia técnica; manter as condições de habilitação; etc.\n**8.2 Obrigações da Contratante:** Efetuar o pagamento no prazo; fiscalizar a execução; notificar a contratada sobre irregularidades; etc.',
      'tr-9': '**9.1 Forma de Seleção:** A seleção do fornecedor será realizada por meio de licitação, na modalidade Pregão, em sua forma Eletrônica, com critério de julgamento de Menor Preço por item.',
      'tr-10': '**10.1 Consórcio:** Não será admitida a participação de empresas em consórcio, tendo em vista a natureza divisível e a não complexidade do objeto.\n**10.2 Cooperativas:** Será permitida a participação de cooperativas, desde que atendam a todos os requisitos de habilitação.',
      'tr-11': '**11.1 Qualificação Técnica:** Será exigida a apresentação de, no mínimo, 1 (um) Atestado de Capacidade Técnica, em nome do licitante, que comprove o fornecimento de equipamentos de informática em quantidade compatível com o objeto desta licitação.',
      'tr-12': '**12.1 Vistoria Técnica:** Não se aplica, pois a simples descrição do objeto no Termo de Referência é suficiente para o perfeito entendimento do objeto a ser contratado.',
      'tr-13': '**13.1 Qualificação Econômico-Financeira:** Os licitantes deverão apresentar Balanço Patrimonial do último exercício social; comprovar Patrimônio Líquido de, no mínimo, 10% do valor estimado da contratação; apresentar certidão negativa de falência.',
      'tr-14': '**14.1 Subcontratação:** Não será admitida a subcontratação do objeto, por se tratar de fornecimento de bens.',
      'tr-15': '**15.1 Gestão e Fiscalização:** A gestão do contrato caberá ao Chefe do Setor de Compras, e a fiscalização técnica será realizada por servidor do Departamento de TI, a ser formalmente designado.',
      'tr-16': '**16.1 Medição e Recebimento:** O recebimento provisório será realizado pelo Almoxarifado no ato da entrega, para verificação quantitativa. O recebimento definitivo será realizado pelo fiscal técnico em até 5 (cinco) dias úteis, após verificação da conformidade com as especificações.',
      'tr-17': '**17.1 Forma de Pagamento:** O pagamento será realizado em parcela única, por meio de crédito em conta corrente, em até 30 (trinta) dias contados da data do recebimento definitivo do objeto e da apresentação da nota fiscal devidamente atestada.',
      'tr-18': '**18.1 Sanções:** Pela inexecução total ou parcial do contrato, a Administração poderá aplicar as seguintes sanções: advertência; multa de 0,5% por dia de atraso na entrega (limitada a 10%); multa de 10% por inexecução parcial; multa de 20% por inexecução total; impedimento de licitar e contratar; declaração de inidoneidade.',
    },
  },
];
