import { Template } from '../types';

export const etpTemplates: Template[] = [
  {
    id: 'etp-ti-equipment',
    name: 'Aquisição de Equipamentos de TI',
    description: 'Template para compra de computadores, notebooks, servidores ou outros equipamentos de informática.',
    type: 'etp',
    sections: {
      'etp-1-introducao': 'Este Estudo Técnico Preliminar (ETP) tem como objetivo planejar e fundamentar a aquisição de novos equipamentos de tecnologia da informação para modernizar o parque tecnológico desta instituição, visando aumentar a produtividade e a segurança da informação.',
      'etp-2-necessidade': 'A demanda atual surge da obsolescência dos equipamentos em uso, que possuem em média mais de 5 anos de utilização. Isso resulta em lentidão, falhas constantes, incompatibilidade com softwares modernos e riscos de segurança, afetando diretamente a performance dos colaboradores e a continuidade dos serviços.',
      'etp-3-requisitos': 'Os equipamentos deverão possuir, no mínimo, as seguintes características: processador de última geração, 16GB de memória RAM, 512GB de armazenamento em SSD e garantia on-site de 3 anos. Devem ser compatíveis com o sistema operacional e softwares já padronizados pela instituição.',
      'etp-4-levantamento': 'Foram consideradas as seguintes soluções:\n1.  **Aquisição de Desktops:** Compra de computadores de mesa tradicionais.\n2.  **Aquisição de Notebooks:** Compra de computadores portáteis.\n3.  **Locação de Equipamentos (HaaS - Hardware as a Service):** Contratação de uma empresa que fornece e mantém os equipamentos por um período determinado.',
      'etp-5-solucao': 'A solução escolhida foi a aquisição de notebooks (Solução 2), pois apresenta o melhor custo-benefício, oferecendo mobilidade para o trabalho híbrido, que se tornou uma realidade na instituição. A locação (Solução 3) tem um custo total de propriedade maior a longo prazo. A aquisição será por meio de licitação na modalidade Pregão Eletrônico, com julgamento por menor preço.',
      'etp-6-estimativa-quantidades': 'Com base no levantamento de necessidades realizado pelo Departamento de TI, estima-se a necessidade de aquisição de 100 (cem) notebooks para atender à demanda de substituição de equipamentos obsoletos e novos postos de trabalho.',
      'etp-7-estimativa-valor': 'A estimativa de valor foi realizada com base em pesquisa de preços no Painel de Preços do Governo Federal, em atas de registro de preços de outros órgãos e em cotações diretas com fornecedores, resultando em um valor estimado de R$ 5.000,00 por unidade, totalizando R$ 500.000,00.',
      'etp-8-justificativa-parcelamento': 'A contratação será realizada em lote único, contemplando todos os 100 notebooks, para garantir a padronização dos equipamentos e obter ganhos de escala na aquisição, resultando em um preço mais vantajoso para a Administração.',
      'etp-9-contratacoes-correlatas': 'Esta contratação está alinhada com a contratação de software de produtividade (Contrato nº XX/YYYY), pois os novos equipamentos garantirão o desempenho adequado das ferramentas.',
      'etp-10-resultados-pretendidos': 'Espera-se uma redução de 50% no número de chamados de suporte técnico relacionados a hardware e um aumento de 20% na produtividade das equipes, conforme medição de desempenho a ser realizada após 6 meses da implantação.',
      'etp-11-providencias': 'Será necessária a capacitação da equipe de TI para o preparo e distribuição dos novos equipamentos. O almoxarifado deverá ser preparado para receber e armazenar os equipamentos até a sua distribuição.',
      'etp-12-impactos-ambientais': 'Os equipamentos a serem adquiridos deverão possuir certificação de eficiência energética (ex: selo Procel ou Energy Star). O descarte dos equipamentos antigos seguirá o plano de logística reversa da instituição, em conformidade com a Política Nacional de Resíduos Sólidos.',
      'etp-13-viabilidade': 'Diante do exposto, a contratação é considerada viável, pois atende a uma necessidade premente da Administração, está alinhada ao planejamento estratégico e possui os recursos orçamentários necessários para sua cobertura.',
    },
  },
  {
    id: 'etp-servicos-engenharia',
    name: '(LICITAÇÃO) Serviços de Engenharia',
    description: 'Template para planejamento da contratação de serviços de engenharia, como elaboração de projetos, fiscalização ou execução de obras.',
    type: 'etp',
    sections: {
      'etp-1-introducao': 'Este ETP visa planejar a contratação de serviços técnicos especializados de engenharia para [DESCREVER O OBJETIVO, EX: a elaboração do projeto executivo de reforma do edifício X]. A contratação se dará por licitação na modalidade [Concorrência/Pregão].',
      'etp-2-necessidade': 'A necessidade da contratação decorre de [DESCREVER O PROBLEMA, EX: da urgência em adequar as instalações do edifício às normas de acessibilidade vigentes, conforme relatório de vistoria nº Y/2024]. A ausência desses serviços impede a correta execução da obra, gerando riscos à segurança e à funcionalidade da edificação.',
      'etp-3-requisitos': 'Os serviços deverão contemplar a elaboração de projetos arquitetônico, elétrico, hidrossanitário e estrutural, com as respectivas anotações de responsabilidade técnica (ART). A empresa contratada deve possuir registro no CREA e comprovar experiência em projetos de complexidade similar.',
      'etp-4-levantamento': 'Foram analisadas as opções de execução direta pela equipe interna, que se mostrou inviável pela falta de especialistas, e a contratação de empresa especializada, que se demonstrou a solução mais adequada para garantir a qualidade e o cumprimento das normas técnicas.',
      'etp-5-solucao': 'A solução consiste na contratação de pessoa jurídica especializada na prestação de serviços de engenharia, por meio de licitação, para elaboração dos projetos necessários, garantindo a expertise técnica e a responsabilidade legal sobre os mesmos.',
      'etp-13-viabilidade': 'A contratação é declarada viável, uma vez que a ausência dos projetos técnicos impede o início de processo licitatório para a obra, sendo esta uma etapa indispensável para o atendimento do interesse público.',
    },
  },
  {
    id: 'etp-servicos-mao-de-obra',
    name: '(LICITAÇÃO) Serviços com dedicação de mão de obra',
    description: 'Ideal para o planejamento de serviços contínuos como limpeza, vigilância, portaria, etc.',
    type: 'etp',
    sections: {
      'etp-1-introducao': 'Este estudo planeja a contratação de serviços contínuos de [TIPO DE SERVIÇO, EX: limpeza, asseio e conservação predial], com dedicação exclusiva de mão de obra, para atender às necessidades das instalações desta instituição.',
      'etp-2-necessidade': 'A contratação é essencial para manter a salubridade, a segurança e o bom funcionamento do ambiente de trabalho, o que impacta diretamente no bem-estar dos servidores e na qualidade do atendimento ao público. O contrato atual está próximo do vencimento, sendo necessária nova contratação para evitar a descontinuidade do serviço.',
      'etp-3-requisitos': 'A contratação deverá prever o quantitativo de postos de trabalho, a carga horária, os insumos e equipamentos necessários. A empresa deverá cumprir rigorosamente a legislação trabalhista e a convenção coletiva da categoria, bem como as normas de saúde e segurança do trabalho.',
      'etp-5-solucao': 'Contratação de empresa especializada, por meio de Pregão Eletrônico, com julgamento pelo menor preço global, para prestação dos serviços de forma contínua, com alocação de postos de trabalho conforme a necessidade detalhada.',
      'etp-6-estimativa-quantidades': 'A estimativa de quantidades baseia-se na área total das instalações ([X] m²), no número de ambientes, no fluxo de pessoas e na produtividade de referência estabelecida na IN SEGES/MPDG nº 5/2017, resultando na necessidade de [N] postos de [função].',
      'etp-10-resultados-pretendidos': 'Espera-se manter o nível de satisfação dos usuários com a limpeza e conservação em patamar superior a 90%, conforme pesquisa de avaliação a ser aplicada semestralmente. Adicionalmente, busca-se a otimização dos custos em relação ao contrato anterior.',
      'etp-13-viabilidade': 'A contratação é viável e indispensável para a manutenção das atividades administrativas e o cumprimento da missão institucional.',
    },
  },
  {
    id: 'etp-fornecimento-continuo',
    name: '(LICITAÇÃO - (inclusive SRP))  Aquisição - Fornecimento contínuo',
    description: 'Planejamento para aquisição de itens de consumo regular, como material de escritório, café ou produtos de limpeza.',
    type: 'etp',
    sections: {
      'etp-1-introducao': 'Este ETP visa planejar a aquisição de [TIPO DE MATERIAL, EX: material de expediente e consumo de escritório], por meio de Sistema de Registro de Preços (SRP), para suprir as necessidades da instituição pelo período de 12 meses.',
      'etp-2-necessidade': 'A demanda por esses materiais é contínua e essencial para o funcionamento de todas as unidades administrativas. O modelo de fornecimento contínuo e por SRP evita a necessidade de grandes estoques e permite a aquisição conforme a demanda real, otimizando recursos.',
      'etp-4-levantamento': 'A alternativa à contratação por SRP seria a realização de múltiplas licitações ao longo do ano, o que geraria maior custo administrativo e risco de desabastecimento. O SRP se mostra mais eficiente e econômico.',
      'etp-6-estimativa-quantidades': 'As quantidades estimadas foram baseadas na média de consumo dos últimos 24 meses, com um acréscimo de 10% para suprir eventuais novas demandas, conforme planilhas de memória de cálculo em anexo.',
      'etp-7-estimativa-valor': 'O valor estimado foi obtido por meio de ampla pesquisa de mercado, utilizando o Painel de Preços, atas de SRP de outros órgãos e cotações com fornecedores, conforme detalhado no mapa de preços anexo.',
      'etp-8-justificativa-parcelamento': 'O objeto será dividido em lotes por categoria de produtos (ex: papelaria, cartuchos, etc.) para ampliar a competitividade e permitir a participação de empresas especializadas em cada segmento.',
      'etp-13-viabilidade': 'A contratação por meio de Sistema de Registro de Preços é viável, vantajosa e adequada para atender à necessidade de fornecimento contínuo dos materiais de consumo.',
    },
  },
];

export const trTemplates: Template[] = [
  {
    id: 'tr-notebooks',
    name: 'Aquisição de Notebooks',
    description: 'Modelo detalhado para a compra de computadores portáteis para uso institucional.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Aquisição de 100 (cem) notebooks, conforme especificações técnicas, condições e prazos estabelecidos neste Termo de Referência e seus anexos. O prazo de garantia mínimo exigido é de 36 (trinta e seis) meses on-site.',
      'tr-2-justificativa': 'A presente contratação justifica-se pela necessidade de modernização do parque computacional, em substituição a equipamentos obsoletos e com baixo desempenho, conforme detalhado no Estudo Técnico Preliminar nº XXX/2024. A aquisição visa prover aos servidores ferramentas de trabalho adequadas, promovendo maior agilidade, mobilidade e segurança no desempenho de suas atividades.',
      'tr-3-natureza-objeto': 'O objeto desta contratação é a aquisição de bens de natureza comum, cujos padrões de desempenho e qualidade podem ser objetivamente definidos por meio de especificações usuais de mercado.',
      'tr-4-execucao-requisitos': 'A entrega dos equipamentos deverá ser realizada em parcela única. O local de entrega será o Almoxarifado Central. A contratada deverá fornecer suporte técnico on-site durante o período da garantia.',
      'tr-5-prazo-execucao': 'O prazo de entrega dos equipamentos será de, no máximo, 30 (trinta) dias corridos, contados a partir do recebimento da Nota de Empenho ou assinatura do contrato.',
      'tr-6-prazo-vigencia': 'O prazo de vigência do contrato será de 12 (doze) meses, contados da sua assinatura, correspondendo ao período para entrega e recebimento dos bens.',
      'tr-7-garantia': 'Será exigida garantia de execução de 5% (cinco por cento) do valor total do contrato, nos moldes do art. 96 da Lei nº 14.133/21.',
      'tr-8-obrigacoes': '**Obrigações da CONTRATADA:**\n- Entregar os equipamentos em perfeito estado de funcionamento e em conformidade com as especificações deste Termo.\n- Prestar a garantia técnica de 36 meses, on-site.\n\n**Obrigações da CONTRATANTE:**\n- Efetuar o pagamento no prazo e condições estabelecidas.\n- Fiscalizar a execução do contrato.',
      'tr-9-selecao-fornecedor': 'A seleção do fornecedor será realizada por meio de Licitação, na modalidade Pregão, em sua forma Eletrônica, com critério de julgamento pelo Menor Preço por item.',
      'tr-10-consorcio-cooperativas': 'Não será permitida a participação de empresas em consórcio. Será permitida a participação de cooperativas que atendam à legislação vigente.',
      'tr-11-qualificacao-tecnica': 'A licitante deverá apresentar Atestado de Capacidade Técnica, emitido por pessoa jurídica de direito público ou privado, que comprove ter fornecido bens de natureza e vulto compatíveis com o objeto desta licitação.',
      'tr-12-vistoria-tecnica': 'Não se aplica a exigência de vistoria técnica para esta contratação.',
      'tr-13-qualificacao-financeira': 'A licitante deverá comprovar boa situação financeira por meio da apresentação de balanço patrimonial e demonstrações contábeis do último exercício social, e possuir patrimônio líquido de, no mínimo, 10% do valor estimado da contratação.',
      'tr-14-subcontratacao': 'Não será admitida a subcontratação do objeto.',
      'tr-15-gestao-contrato': 'A gestão e fiscalização do contrato serão realizadas por servidor(a) ou comissão designada pela autoridade competente, que será responsável por acompanhar a entrega, atestar o recebimento dos equipamentos e comunicar quaisquer ocorrências à Administração.',
      'tr-16-medicao-recebimento': 'O objeto será recebido provisoriamente no ato da entrega para verificação da conformidade com as especificações e, definitivamente, em até 5 dias úteis após o recebimento provisório.',
      'tr-17-forma-pagamento': 'O pagamento será efetuado em parcela única, no prazo de até 30 (trinta) dias após o recebimento definitivo dos equipamentos, mediante a apresentação da correspondente nota fiscal devidamente atestada pelo fiscal do contrato.',
      'tr-18-sancoes': 'O descumprimento total ou parcial das obrigações assumidas sujeitará a contratada às sanções previstas no Capítulo II do Título IV da Lei nº 14.133/2021, garantido o contraditório e a ampla defesa.',
      'tr-19-sustentabilidade': 'Os equipamentos deverão possuir certificação de eficiência energética (selo Procel ou Energy Star). As embalagens deverão ser de material reciclado ou reciclável.',
      'tr-20-orcamento': 'As despesas decorrentes da presente contratação correrão à conta da Ação Orçamentária [Número], Fonte [Número], Elemento de Despesa [Número].',
      'tr-21-consideracoes-finais': 'Este Termo de Referência foi elaborado com base no Estudo Técnico Preliminar nº XXX/2024 e segue as diretrizes da Lei nº 14.133/2021.',
      'tr-22-anexos': 'Anexo I - Especificações Técnicas Mínimas dos Notebooks.\nAnexo II - Minuta da Ata de Registro de Preços/Contrato.\nAnexo III - Modelo de Proposta.',
    },
  },
  {
    id: 'tr-servicos-engenharia',
    name: '(LICITAÇÃO) Serviços de Engenharia',
    description: 'Modelo para especificar a contratação de serviços técnicos de engenharia, como projetos, fiscalização ou gerenciamento de obras.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Contratação de empresa especializada em engenharia para [DESCREVER O SERVIÇO, EX: elaboração do projeto executivo de climatização do auditório principal], conforme especificações e condições deste Termo de Referência e seus anexos.',
      'tr-2-justificativa': 'A contratação é necessária para garantir a expertise técnica na elaboração de um projeto complexo, assegurando o cumprimento de normas técnicas e a melhor solução de engenharia para a demanda, conforme justificado no ETP nº XXX/2024.',
      'tr-4-execucao-requisitos': 'O serviço será executado em etapas: 1. Estudo Preliminar; 2. Anteprojeto; 3. Projeto Executivo. Cada etapa deverá ser aprovada pelo fiscal do contrato para que a subsequente seja iniciada. Todos os projetos devem ser entregues em formato digital (DWG e PDF) e plotados.',
      'tr-8-obrigacoes': 'A Contratada deverá fornecer a Anotação de Responsabilidade Técnica (ART) de todos os projetos. A Contratante deverá fornecer todas as informações e acesso ao local necessários para a elaboração dos estudos.',
      'tr-9-selecao-fornecedor': 'Licitação na modalidade Concorrência, critério de julgamento por Técnica e Preço, dada a natureza predominantemente intelectual do serviço.',
      'tr-11-qualificacao-tecnica': 'Exigência de atestados que comprovem a execução de projetos de complexidade e porte similar ao objeto licitado. A equipe técnica deverá contar com ao menos um engenheiro civil e um engenheiro eletricista com X anos de experiência.',
      'tr-15-gestao-contrato': 'A fiscalização será realizada por engenheiro do quadro da contratante, que será responsável por aprovar as etapas, medir os serviços e atestar as notas fiscais.',
    },
  },
  {
    id: 'tr-servicos-mao-de-obra',
    name: '(LICITAÇÃO) Serviços com dedicação de mão de obra',
    description: 'Modelo para especificar serviços contínuos como limpeza, vigilância, etc., com foco no gerenciamento dos postos de trabalho.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Prestação de serviços contínuos de [TIPO DE SERVIÇO], com regime de dedicação exclusiva de mão de obra, compreendendo [X] postos de [FUNÇÃO], com carga horária de [Y] horas semanais.',
      'tr-2-justificativa': 'Referência ao Estudo Técnico Preliminar nº XXX/2024, que detalha a necessidade de manutenção da continuidade e qualidade dos serviços de [TIPO DE SERVIÇO] para o bom funcionamento da instituição.',
      'tr-4-execucao-requisitos': 'A contratada deverá alocar o pessoal nos locais e horários definidos, fornecer uniformes e EPIs, e realizar a substituição de funcionários ausentes em até [Z] horas. O serviço será medido com base no Instrumento de Medição de Resultado (IMR) anexo.',
      'tr-8-obrigacoes': 'A Contratada deve comprovar mensalmente o pagamento de salários e encargos trabalhistas e previdenciários dos funcionários alocados. A Contratante deve garantir as condições adequadas para a prestação do serviço e realizar o pagamento mediante o cumprimento das metas do IMR.',
      'tr-9-selecao-fornecedor': 'Pregão Eletrônico com critério de julgamento por Menor Preço Global do Lote.',
      'tr-15-gestao-contrato': 'A gestão do contrato será realizada por um fiscal técnico, um fiscal administrativo e um gestor de contrato. O fiscal técnico acompanhará a execução no local, enquanto o administrativo verificará o cumprimento das obrigações trabalhistas.',
      'tr-17-forma-pagamento': 'O pagamento será mensal, após o término do mês de prestação de serviço, condicionado à apresentação da documentação comprobatória das obrigações trabalhistas e ao ateste do fiscal com base no IMR.',
    },
  },
  {
    id: 'tr-srp-servicos-sem-residente',
    name: '(LICITAÇÃO SRP) Serviços sem Mão de obra Residente',
    description: 'Para serviços sob demanda via Sistema de Registro de Preços, como manutenção corretiva, chaveiro, etc.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Registro de Preços para a contratação de serviços de [TIPO DE SERVIÇO, EX: manutenção corretiva de ar-condicionado], a serem executados sob demanda, conforme as especificações e quantitativos máximos estabelecidos neste Termo e seus anexos.',
      'tr-4-execucao-requisitos': 'A execução dos serviços ocorrerá mediante a emissão de Ordens de Serviço (OS) pela Contratante. A Contratada terá o prazo de [X] horas para atender ao chamado e [Y] horas para solucionar o problema. Os serviços serão medidos por unidade de intervenção ou hora técnica, conforme definido na planilha de preços.',
      'tr-9-selecao-fornecedor': 'Pregão Eletrônico para Registro de Preços, com julgamento por Menor Preço por Item.',
      'tr-15-gestao-contrato': 'A gestão do contrato e da Ata de Registro de Preços será realizada por um gestor designado, que será responsável por emitir as Ordens de Serviço e atestar a sua correta execução para fins de pagamento.',
      'tr-16-medicao-recebimento': 'Cada Ordem de Serviço será recebida individualmente, mediante termo de recebimento assinado pelo fiscal técnico após a comprovação da solução do problema e do cumprimento dos SLAs (níveis de serviço).',
    },
  },
  {
    id: 'tr-servicos-sem-dedicada',
    name: '(LICITAÇÃO) Serviços sem mão de obra dedicada',
    description: 'Para serviços pagos por resultado, sem alocação de postos fixos, como coleta de resíduos, controle de pragas, etc.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Contratação de empresa para prestação de serviços de [TIPO DE SERVIÇO, EX: controle de vetores e pragas urbanas], a serem realizados de forma periódica e eventual, sem dedicação exclusiva de mão de obra.',
      'tr-4-execucao-requisitos': 'Os serviços serão executados conforme cronograma (ex: uma aplicação a cada 3 meses) e por demanda para atendimentos emergenciais. A empresa deverá apresentar um plano de trabalho e utilizar produtos e técnicas em conformidade com as normas da ANVISA.',
      'tr-9-selecao-fornecedor': 'Pregão Eletrônico, com julgamento por Menor Preço Global.',
      'tr-15-gestao-contrato': 'A fiscalização será baseada nos resultados. O fiscal verificará, por meio de relatórios e vistorias, se o serviço foi executado nas datas programadas e se o resultado esperado (ex: ausência de pragas) foi alcançado.',
      'tr-16-medicao-recebimento': 'O pagamento será realizado após a comprovação da execução de cada etapa do cronograma (ex: pagamento trimestral após a aplicação) e do ateste do fiscal sobre a qualidade do serviço prestado.',
    },
  },
  {
    id: 'tr-srp-fornecimento-continuo',
    name: '(LICITAÇÃO - (inclusive SRP)) Aquisição - Fornecimento contínuo',
    description: 'Especificação de itens de consumo regular (material de escritório, etc.) para contratação via SRP.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Registro de Preços para eventual aquisição de [TIPO DE MATERIAL, EX: material de expediente e consumo de escritório], conforme especificações, quantitativos máximos e condições estabelecidas neste Termo de Referência.',
      'tr-4-execucao-requisitos': 'O fornecimento será realizado de forma parcelada, mediante solicitação da Contratante através da emissão de Nota de Empenho e Ordem de Fornecimento. O local de entrega será no Almoxarifado Central.',
      'tr-5-prazo-execucao': 'O prazo de entrega de cada solicitação será de, no máximo, [X] dias úteis, contados do recebimento da Ordem de Fornecimento pela Contratada.',
      'tr-6-prazo-vigencia': 'A Ata de Registro de Preços terá vigência de 12 (doze) meses, podendo ser prorrogada por igual período.',
      'tr-9-selecao-fornecedor': 'Pregão Eletrônico para Registro de Preços, com julgamento por Menor Preço por Item.',
      'tr-15-gestao-contrato': 'O gestor da Ata será responsável por autorizar as aquisições e controlar para que os quantitativos totais não sejam ultrapassados. O recebimento e conferência dos materiais serão feitos pelo setor de Almoxarifado.',
    },
  },
  {
    id: 'tr-dispensa-fornecimento-continuo',
    name: '(Dispensa eletrônica) Aquisição - Fornecimento contínuo',
    description: 'Para contratação direta (dispensa de licitação) de itens de consumo, como água mineral, gás, etc.',
    type: 'tr',
    sections: {
      'tr-1-objeto': 'Aquisição de [TIPO DE MATERIAL, EX: galões de água mineral de 20 litros], para consumo contínuo nas dependências da instituição.',
      'tr-2-justificativa': 'A contratação por dispensa de licitação se justifica com base no Art. 75, Inciso II da Lei 14.133/21, dado que o valor estimado da contratação anual está abaixo do limite estabelecido. A aquisição é essencial para garantir o bem-estar de servidores e do público atendido.',
      'tr-4-execucao-requisitos': 'O fornecimento será sob demanda. A contratada deverá realizar as entregas no prazo de 24 horas após a solicitação, no endereço da instituição.',
      'tr-9-selecao-fornecedor': 'Contratação Direta por Dispensa de Licitação, na forma eletrônica. Será selecionada a proposta de menor preço, desde que compatível com os valores de mercado.',
      'tr-17-forma-pagamento': 'O pagamento será mensal, correspondente à quantidade de itens efetivamente entregues no mês, mediante apresentação de nota fiscal atestada.',
    },
  },
];